--------------------------------------------------------
--  File created - Tuesday-November-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITY_STATE
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."CITY_STATE" 
   (	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(*,0), 
	"LNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"AGE" NUMBER(*,0), 
	"PHONE" VARCHAR2(15 BYTE), 
	"CARD_NO" VARCHAR2(20 BYTE), 
	"MEMBERSHIP_ID" NUMBER(*,0), 
	"MEMBERSHIP_BEGIN_DT" DATE, 
	"APT_NO" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(*,0), 
	"MEMBERSHIP_STATUS" VARCHAR2(20 BYTE), 
	"MEMBERSHIP_END_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."EMPLOYEE" 
   (	"SSN" VARCHAR2(9 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"MGR_SSN" VARCHAR2(9 BYTE), 
	"SALARY" NUMBER(10,2), 
	"SEX" VARCHAR2(20 BYTE), 
	"APT_NO" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIP_GAME
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."EQUIP_GAME" 
   (	"EQUIPMENT_NAME" VARCHAR2(20 BYTE), 
	"GAME_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GAME
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."GAME" 
   (	"GAME_ID" NUMBER(*,0), 
	"GAME_NAME" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"AGE_LIMIT" NUMBER(*,0), 
	"PRICE_HR" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GAME_EQUIPMENT
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."GAME_EQUIPMENT" 
   (	"EQUIPMENT_ID" NUMBER(*,0), 
	"EQUIPMENT_NAME" VARCHAR2(20 BYTE), 
	"BRANCH_ID" NUMBER(*,0), 
	"AVAILABLE_UNITS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOSTS
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."HOSTS" 
   (	"BRANCH_ID" NUMBER(*,0), 
	"GAME_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERSHIP_DETAILS
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."MEMBERSHIP_DETAILS" 
   (	"MEMBERSHIP_ID" NUMBER(*,0), 
	"MEMBERSHIP_TYPE" VARCHAR2(20 BYTE), 
	"VALIDITY" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(5,2), 
	"DISCOUNT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MGR_BRANCH
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."MGR_BRANCH" 
   (	"MGR_SSN" VARCHAR2(9 BYTE), 
	"BRANCH_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYGROUND_BRANCH
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."PLAYGROUND_BRANCH" 
   (	"BRANCH_ID" NUMBER(*,0), 
	"MGR_SSN" VARCHAR2(9 BYTE), 
	"OPENING_TIME" TIMESTAMP (6), 
	"CLOSING_TIME" TIMESTAMP (6), 
	"SIZE_SQ_FT" VARCHAR2(20 BYTE), 
	"GROUND_TYPE" VARCHAR2(20 BYTE), 
	"BLDG_NO" VARCHAR2(20 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTERS
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."REGISTERS" 
   (	"CUSTOMER_ID" NUMBER(*,0), 
	"GAME_ID" NUMBER(*,0), 
	"BILL_ID" NUMBER(*,0), 
	"BILL_DATE" DATE, 
	"PAYMENT_TYPE" VARCHAR2(20 BYTE), 
	"TOTAL_AMOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOY
--------------------------------------------------------

  CREATE TABLE "C##SANDEEP"."TOY" 
   (	"TOY_ID" NUMBER(*,0), 
	"TOY_NAME" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View DEPT_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##SANDEEP"."DEPT_DETAILS" ("DNAME", "FNAME", "LNAME", "NO_OF_EMP", "NO_OF_PROJ") AS 
  SELECT D.DNAME, M.FNAME, M.LNAME, 
      (SELECT COUNT(E.SSN) FROM EMPLOYEE E WHERE E.DNO = D.DNO) AS NO_OF_EMP, 
      (SELECT COUNT(P.PNO) FROM PROJECT P WHERE P.DNO = D.DNO) AS NO_OF_PROJ
    FROM DEPARTMENT D, EMPLOYEE M
    WHERE M.SSN = D.MGRSSN;
--------------------------------------------------------
--  DDL for View EMP_MGR_DEPT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##SANDEEP"."EMP_MGR_DEPT" ("FNAME", "LNAME", "SALARY", "DEPT_NAME", "MGR_FNAME", "MGR_LNAME", "MGR_SALARY", "DEPT_AVG_SAL") AS 
  SELECT E.FNAME, E.LNAME, E.SALARY, (SELECT D.DNAME FROM DEPARTMENT D WHERE D.DNO = E.DNO) AS DEPT_NAME,
    (SELECT M.FNAME FROM EMPLOYEE M, DEPARTMENT P WHERE M.SSN = P.MGRSSN AND P.DNO = E.DNO) AS MGR_FNAME,
    (SELECT X.LNAME FROM EMPLOYEE X, DEPARTMENT Y WHERE X.SSN = Y.MGRSSN AND Y.DNO = E.DNO) AS MGR_LNAME,
    (SELECT J.SALARY FROM EMPLOYEE J, DEPARTMENT Z WHERE J.SSN = Z.MGRSSN AND Z.DNO = E.DNO) AS MGR_SALARY,
    (SELECT AVG(A.SALARY) FROM EMPLOYEE A WHERE A.DNO = E.DNO) DEPT_AVG_SAL
    FROM EMPLOYEE E;
--------------------------------------------------------
--  DDL for View MANAGER_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##SANDEEP"."MANAGER_DETAILS" ("DNAME", "FNAME", "LNAME", "SALARY") AS 
  SELECT D.DNAME,M.FNAME,M.LNAME,M.SALARY
    FROM DEPARTMENT D, EMPLOYEE M
    WHERE  M.SSN = D.MGRSSN;
--------------------------------------------------------
--  DDL for View PROJ_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##SANDEEP"."PROJ_DETAILS" ("PNAME", "DEPT_NAME", "NO_OF_EMP", "HOURS_PER_WEEK") AS 
  SELECT P.PNAME, (SELECT D.DNAME FROM DEPARTMENT D WHERE D.DNO = P.DNO) AS DEPT_NAME,
    (SELECT COUNT(W.SSN) FROM WORKS_ON W WHERE W.PNO = P.PNO) AS NO_OF_EMP,
    (SELECT SUM(H.HOURS) FROM WORKS_ON H WHERE H.PNO = P.PNO) AS HOURS_PER_WEEK
    FROM PROJECT P;
--------------------------------------------------------
--  DDL for View PROJ_EMP_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##SANDEEP"."PROJ_EMP_DETAILS" ("PNAME", "DEPT_NAME", "NO_OF_EMP", "TOTAL_WORK_HRS") AS 
  SELECT P.PNAME, (SELECT D.DNAME FROM DEPARTMENT D WHERE D.DNO = P.DNO) AS DEPT_NAME,
    (SELECT COUNT(W.SSN) FROM WORKS_ON W WHERE W.PNO = P.PNO) AS NO_OF_EMP,
    (SELECT SUM(H.HOURS) FROM WORKS_ON H WHERE H.PNO = P.PNO) AS TOTAL_WORK_HRS
    FROM PROJECT P
    WHERE P.PNO IN (SELECT J.PNO FROM WORKS_ON J GROUP BY J.PNO HAVING COUNT(J.SSN) > 1 );
REM INSERTING into C##SANDEEP.CITY_STATE
SET DEFINE OFF;
Insert into C##SANDEEP.CITY_STATE (CITY,STATE) values ('Richardson','Texas');
Insert into C##SANDEEP.CITY_STATE (CITY,STATE) values ('Dallas','Texas');
Insert into C##SANDEEP.CITY_STATE (CITY,STATE) values ('Los Angeles','California');
Insert into C##SANDEEP.CITY_STATE (CITY,STATE) values ('Chicago','Illinois');
REM INSERTING into C##SANDEEP.CUSTOMER
SET DEFINE OFF;
Insert into C##SANDEEP.CUSTOMER (CUSTOMER_ID,LNAME,FNAME,AGE,PHONE,CARD_NO,MEMBERSHIP_ID,MEMBERSHIP_BEGIN_DT,APT_NO,STREET,CITY,PINCODE,MEMBERSHIP_STATUS,MEMBERSHIP_END_DT) values (1,'Vaddi','Sai Sandeep',23,'6824722966','1234 1234 1234 1234',1,to_date('30-OCT-16','DD-MON-RR'),'123','Mc Callum Blvd','Dallas',775252,null,null);
REM INSERTING into C##SANDEEP.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into C##SANDEEP.EQUIP_GAME
SET DEFINE OFF;
Insert into C##SANDEEP.EQUIP_GAME (EQUIPMENT_NAME,GAME_ID) values ('Table Tennis',2);
REM INSERTING into C##SANDEEP.GAME
SET DEFINE OFF;
Insert into C##SANDEEP.GAME (GAME_ID,GAME_NAME,TYPE,AGE_LIMIT,PRICE_HR) values (1,'Safari','S',10,5);
Insert into C##SANDEEP.GAME (GAME_ID,GAME_NAME,TYPE,AGE_LIMIT,PRICE_HR) values (2,'Table Tennis','SD',5,10);
REM INSERTING into C##SANDEEP.GAME_EQUIPMENT
SET DEFINE OFF;
Insert into C##SANDEEP.GAME_EQUIPMENT (EQUIPMENT_ID,EQUIPMENT_NAME,BRANCH_ID,AVAILABLE_UNITS) values (2,'Table Tennis',1,10);
REM INSERTING into C##SANDEEP.HOSTS
SET DEFINE OFF;
Insert into C##SANDEEP.HOSTS (BRANCH_ID,GAME_ID) values (1,1);
Insert into C##SANDEEP.HOSTS (BRANCH_ID,GAME_ID) values (1,2);
REM INSERTING into C##SANDEEP.MEMBERSHIP_DETAILS
SET DEFINE OFF;
Insert into C##SANDEEP.MEMBERSHIP_DETAILS (MEMBERSHIP_ID,MEMBERSHIP_TYPE,VALIDITY,PRICE,DISCOUNT) values (1,'Platinum','1 y',100,30);
Insert into C##SANDEEP.MEMBERSHIP_DETAILS (MEMBERSHIP_ID,MEMBERSHIP_TYPE,VALIDITY,PRICE,DISCOUNT) values (2,'Gold','6 m',50,20);
Insert into C##SANDEEP.MEMBERSHIP_DETAILS (MEMBERSHIP_ID,MEMBERSHIP_TYPE,VALIDITY,PRICE,DISCOUNT) values (3,'Silver','3 m',25,10);
REM INSERTING into C##SANDEEP.MGR_BRANCH
SET DEFINE OFF;
Insert into C##SANDEEP.MGR_BRANCH (MGR_SSN,BRANCH_NAME) values ('222222200','Dallas');
REM INSERTING into C##SANDEEP.PLAYGROUND_BRANCH
SET DEFINE OFF;
Insert into C##SANDEEP.PLAYGROUND_BRANCH (BRANCH_ID,MGR_SSN,OPENING_TIME,CLOSING_TIME,SIZE_SQ_FT,GROUND_TYPE,BLDG_NO,STREET,CITY,PINCODE) values (1,'222222200',null,null,null,null,'101','W.Renner Rd','Dallas',75050);
REM INSERTING into C##SANDEEP.REGISTERS
SET DEFINE OFF;
Insert into C##SANDEEP.REGISTERS (CUSTOMER_ID,GAME_ID,BILL_ID,BILL_DATE,PAYMENT_TYPE,TOTAL_AMOUNT) values (1,2,1,to_date('29-NOV-16','DD-MON-RR'),'CREDIT CARD',20);
Insert into C##SANDEEP.REGISTERS (CUSTOMER_ID,GAME_ID,BILL_ID,BILL_DATE,PAYMENT_TYPE,TOTAL_AMOUNT) values (1,1,null,to_date('29-NOV-16','DD-MON-RR'),'CREDIT CARD',30);
REM INSERTING into C##SANDEEP.TOY
SET DEFINE OFF;
Insert into C##SANDEEP.TOY (TOY_ID,TOY_NAME,CUSTOMER_ID) values (1,'Spiderman',1);
--------------------------------------------------------
--  DDL for Index SYS_C0010627
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010627" ON "C##SANDEEP"."CITY_STATE" ("CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010644
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010644" ON "C##SANDEEP"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010665
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010665" ON "C##SANDEEP"."EMPLOYEE" ("SSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010652
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010652" ON "C##SANDEEP"."EQUIP_GAME" ("EQUIPMENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010623
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010623" ON "C##SANDEEP"."GAME" ("GAME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010655
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010655" ON "C##SANDEEP"."GAME_EQUIPMENT" ("EQUIPMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010638
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010638" ON "C##SANDEEP"."HOSTS" ("BRANCH_ID", "GAME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010626
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010626" ON "C##SANDEEP"."MEMBERSHIP_DETAILS" ("MEMBERSHIP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010630
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010630" ON "C##SANDEEP"."MGR_BRANCH" ("MGR_SSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010633
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010633" ON "C##SANDEEP"."PLAYGROUND_BRANCH" ("BRANCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010658
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010658" ON "C##SANDEEP"."REGISTERS" ("CUSTOMER_ID", "GAME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010648
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SANDEEP"."SYS_C0010648" ON "C##SANDEEP"."TOY" ("TOY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CITY_STATE
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."CITY_STATE" ADD PRIMARY KEY ("CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."CUSTOMER" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."CUSTOMER" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."CUSTOMER" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."EMPLOYEE" ADD PRIMARY KEY ("SSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."EMPLOYEE" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."EMPLOYEE" MODIFY ("MNAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."EMPLOYEE" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."EMPLOYEE" MODIFY ("SSN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIP_GAME
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."EQUIP_GAME" ADD PRIMARY KEY ("EQUIPMENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."EQUIP_GAME" MODIFY ("GAME_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."EQUIP_GAME" MODIFY ("EQUIPMENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GAME
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."GAME" ADD PRIMARY KEY ("GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."GAME" MODIFY ("GAME_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."GAME" MODIFY ("GAME_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GAME_EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."GAME_EQUIPMENT" ADD PRIMARY KEY ("EQUIPMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."GAME_EQUIPMENT" MODIFY ("EQUIPMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOSTS
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."HOSTS" ADD PRIMARY KEY ("BRANCH_ID", "GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."HOSTS" MODIFY ("GAME_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."HOSTS" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBERSHIP_DETAILS
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."MEMBERSHIP_DETAILS" ADD PRIMARY KEY ("MEMBERSHIP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."MEMBERSHIP_DETAILS" MODIFY ("MEMBERSHIP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."MEMBERSHIP_DETAILS" MODIFY ("MEMBERSHIP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MGR_BRANCH
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."MGR_BRANCH" ADD PRIMARY KEY ("MGR_SSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."MGR_BRANCH" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."MGR_BRANCH" MODIFY ("MGR_SSN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYGROUND_BRANCH
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."PLAYGROUND_BRANCH" ADD PRIMARY KEY ("BRANCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."PLAYGROUND_BRANCH" MODIFY ("MGR_SSN" NOT NULL ENABLE);
  ALTER TABLE "C##SANDEEP"."PLAYGROUND_BRANCH" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTERS
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."REGISTERS" ADD PRIMARY KEY ("CUSTOMER_ID", "GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TOY
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."TOY" ADD PRIMARY KEY ("TOY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SANDEEP"."TOY" MODIFY ("TOY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."CUSTOMER" ADD FOREIGN KEY ("MEMBERSHIP_ID")
	  REFERENCES "C##SANDEEP"."MEMBERSHIP_DETAILS" ("MEMBERSHIP_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##SANDEEP"."CUSTOMER" ADD FOREIGN KEY ("CITY")
	  REFERENCES "C##SANDEEP"."CITY_STATE" ("CITY") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."EMPLOYEE" ADD FOREIGN KEY ("CITY")
	  REFERENCES "C##SANDEEP"."CITY_STATE" ("CITY") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##SANDEEP"."EMPLOYEE" ADD FOREIGN KEY ("MGR_SSN")
	  REFERENCES "C##SANDEEP"."MGR_BRANCH" ("MGR_SSN") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIP_GAME
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."EQUIP_GAME" ADD FOREIGN KEY ("GAME_ID")
	  REFERENCES "C##SANDEEP"."GAME" ("GAME_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GAME_EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."GAME_EQUIPMENT" ADD FOREIGN KEY ("EQUIPMENT_NAME")
	  REFERENCES "C##SANDEEP"."EQUIP_GAME" ("EQUIPMENT_NAME") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##SANDEEP"."GAME_EQUIPMENT" ADD FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "C##SANDEEP"."PLAYGROUND_BRANCH" ("BRANCH_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOSTS
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."HOSTS" ADD FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "C##SANDEEP"."PLAYGROUND_BRANCH" ("BRANCH_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##SANDEEP"."HOSTS" ADD FOREIGN KEY ("GAME_ID")
	  REFERENCES "C##SANDEEP"."GAME" ("GAME_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAYGROUND_BRANCH
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."PLAYGROUND_BRANCH" ADD FOREIGN KEY ("CITY")
	  REFERENCES "C##SANDEEP"."CITY_STATE" ("CITY") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##SANDEEP"."PLAYGROUND_BRANCH" ADD FOREIGN KEY ("MGR_SSN")
	  REFERENCES "C##SANDEEP"."MGR_BRANCH" ("MGR_SSN") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTERS
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."REGISTERS" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "C##SANDEEP"."CUSTOMER" ("CUSTOMER_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##SANDEEP"."REGISTERS" ADD FOREIGN KEY ("GAME_ID")
	  REFERENCES "C##SANDEEP"."GAME" ("GAME_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOY
--------------------------------------------------------

  ALTER TABLE "C##SANDEEP"."TOY" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "C##SANDEEP"."CUSTOMER" ("CUSTOMER_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  DDL for Procedure GENERATE_BILL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##SANDEEP"."GENERATE_BILL" (Customer_Id IN CUSTOMER.Customer_Id%TYPE)
IS
Game_Id GAME.Game_Id%TYPE;
Customer_Lname CUSTOMER.LNAME%TYPE;
Customer_Fname CUSTOMER.FNAME%TYPE;
Game_Bill NUMBER(10,2);
Bill NUMBER(10,2);
Price_per_hr GAME.Price_Hr%TYPE;
Membership MEMBERSHIP_DETAILS.MEMBERSHIP_TYPE%TYPE;
Discount_Amt MEMBERSHIP_DETAILS.DISCOUNT%TYPE;
Game_Name GAME.Game_Name%TYPE;
CURSOR REGISTER_DETAILS IS
	SELECT R.game_id, R.total_amount FROM REGISTERS R WHERE R.CUSTOMER_ID = Customer_Id AND BILL_DATE = trunc(SYSDATE);
BEGIN
	SELECT LNAME, FNAME into Customer_Lname, Customer_Fname FROM CUSTOMER C WHERE C.Customer_Id = Customer_Id;
	SELECT DISCOUNT, MEMBERSHIP_TYPE INTO Discount_Amt, Membership FROM MEMBERSHIP_DETAILS WHERE MEMBERSHIP_ID = (SELECT MEMBERSHIP_ID FROM CUSTOMER C WHERE C.CUSTOMER_ID = Customer_Id); 
	DBMS_OUTPUT.PUT_LINE('Customer Name: '||Customer_Lname||', '||Customer_Fname);
	DBMS_OUTPUT.PUT_LINE('Game Id'||' '||'Game Name'||' '||'Hrs Played'||' '||'Bill by Game');
	OPEN REGISTER_DETAILS;
	LOOP
		FETCH REGISTER_DETAILS INTO Game_Id, Game_Bill;
		EXIT WHEN REGISTER_DETAILS%NOTFOUND;
		SELECT G.Game_Name, G.Price_Hr into Game_Name, Price_per_hr FROM GAME G WHERE G.Game_Id = Game_Id;
		DBMS_OUTPUT.PUT_LINE(Game_Id||' '||Game_Name||' '||(Game_Bill/Price_per_Hr)||' '||Game_Bill);
		Bill := Bill + Game_Bill;
	END LOOP;
	CLOSE REGISTER_DETAILS;
	DBMS_OUTPUT.PUT_LINE('Total Amount: '||Bill);
	DBMS_OUTPUT.PUT_LINE('Membership: '||Membership);
	Bill := Bill - (Bill * (Discount_Amt/100));
	DBMS_OUTPUT.PUT_LINE('Discount %'||Discount_Amt);
	DBMS_OUTPUT.PUT_LINE('Final Bill'||Bill);
	Bill := 0;		
END GENERATE_BILL;

/
