INSERT INTO GAME (GAME_ID, GAME_NAME, TYPE, AGE_LIMIT, PRICE_HR) VALUES (1, 'Safari', 'S', 10, 5);
INSERT INTO GAME (GAME_ID, GAME_NAME, TYPE, AGE_LIMIT, PRICE_HR) VALUES (2, 'Table Tennis', 'SD', 5, 10);




INSERT INTO MEMBERSHIP_DETAILS (MEMBERSHIP_ID, MEMBERSHIP_TYPE, STATUS, VALIDITY, PRICE) VALUES (1, 'Platinum', '', '1 y', 100); 
INSERT INTO MEMBERSHIP_DETAILS (MEMBERSHIP_ID, MEMBERSHIP_TYPE, STATUS, VALIDITY, PRICE) VALUES (2, 'Gold', '', '6 m', 50);
INSERT INTO MEMBERSHIP_DETAILS (MEMBERSHIP_ID, MEMBERSHIP_TYPE, STATUS, VALIDITY, PRICE) VALUES (3, 'Silver', '', '3 m', 25);




INSERT INTO CITY_STATE (CITY, STATE) VALUES ('Richardson', 'Texas');
INSERT INTO CITY_STATE (CITY, STATE) VALUES ('Dallas', 'Texas');
INSERT INTO CITY_STATE (CITY, STATE) VALUES ('Los Angeles', 'California');
INSERT INTO CITY_STATE (CITY, STATE) VALUES ('Chicago', 'Illinois');



INSERT INTO MGR_BRANCH (MGR_SSN, BRANCH_NAME) VALUES ('222222200', 'Dallas');


INSERT INTO "PLAYGROUND_BRANCH" (BRANCH_ID, MGR_SSN, BLDG_NO, STREET, CITY, PINCODE) VALUES ('1', '222222200', '101', 'W.Renner Rd', 'Dallas', '75050');


INSERT INTO "C##SANDEEP"."HOSTS" (BRANCH_ID, GAME_ID) VALUES ('1', '1');
INSERT INTO "C##SANDEEP"."HOSTS" (BRANCH_ID, GAME_ID) VALUES ('1', '2');

INSERT INTO "C##SANDEEP"."CUSTOMER" (CUSTOMER_ID, LNAME, FNAME, AGE, PHONE, CARD_NO, MEMBERSHIP_ID, MEMBERSHIP_BEGIN_DT, APT_NO, STREET, CITY, PINCODE) VALUES ('1', 'Vaddi', 'Sai Sandeep', '23', '6824722966', '1234 1234 1234 1234', '1', TO_DATE('2016-10-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '123', 'Mc Callum Blvd', 'Dallas', '775252');



INSERT INTO "C##SANDEEP"."TOY" (TOY_ID, TOY_NAME, CUSTOMER_ID) VALUES ('1', 'Spiderman', '1');
INSERT INTO "C##SANDEEP"."EQUIP_GAME" (EQUIPMENT_NAME, GAME_ID) VALUES ('Table Tennis', '2');

INSERT INTO "C##SANDEEP"."GAME_EQUIPMENT" (EQUIPMENT_ID, EQUIPMENT_NAME, BRANCH_ID, AVAILABLE_UNITS) VALUES ('2', 'Table Tennis', '1', '10');

INSERT INTO "C##SANDEEP"."REGISTERS" (CUSTOMER_ID, GAME_ID, BILL_ID, BILL_DATE, PAYMENT_TYPE, TOTAL_AMOUNT) VALUES ('1', '2', '1', TO_DATE('2016-11-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'CREDIT CARD', '20');
INSERT INTO "C##SANDEEP"."REGISTERS" (CUSTOMER_ID, GAME_ID, BILL_DATE, PAYMENT_TYPE, TOTAL_AMOUNT) VALUES ('1', '1', TO_DATE('2016-11-29 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'CREDIT CARD', '30');










INSERT INTO EMPLOYEE
	(SSN, LNAME, MNAME, FNAME, MGR_SSN, SALARY, SEX, APT_NO, STREET, CITY, PINCODE)
VALUES
	('222222202', 'Vile', 'C', 'Andy', '222222200', 53000, 'M', '101', 'Street1', 'Dallas', '75080');