DROP TRIGGER GAME_EQUIPMENT_AVAILABILYT;
CREATE OR REPLACE TRIGGER GAME_EQUIPMENT_AVAILABILYT
  AFTER UPDATE OF AVAILABLE_UNITS ON GAME_EQUIPMENT 
  FOR EACH ROW
  DECLARE 
  AVA_QNTY NUMBER;
  B_ID NUMBER;
  E_NAME VARCHAR(20);
  G_ID NUMBER;
BEGIN
 CASE
 WHEN UPDATING('AVAILABLE_UNITS') 
 THEN
 IF(:NEW.AVAILABLE_UNITS = 0) THEN
 B_ID :=:NEW.BRANCH_ID;
 E_NAME := :NEW.EQUIPMENT_NAME;
 SELECT S.GAME_ID INTO G_ID FROM  EQUIP_GAME S WHERE E_NAME=S.EQUIPMENT_NAME;
 
  DELETE FROM HOSTS L WHERE L.BRANCH_ID= B_ID AND G_ID=L.GAME_ID;

  END IF;
  

UPDATE GAME_EQUIPMENT
SET AVAILABLE_UNITS=0 
WHERE BRANCH_ID =1;